<?php

namespace AdresseBundle\Repository;

/**
 * carnetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class carnetRepository extends \Doctrine\ORM\EntityRepository
{
}
